---

- name: Upload the CoreOS image if it's present locally but not remotelly 
  os_image:
    name: "{{ rhcos_image_name }}"
    cloud: "{{ openstack_cloud_name }}"
    state: present
    container_format: bare
    disk_format: qcow2
    filename: "{{ rhcos_image_file }}"
  when: (openstack_rhcos_image_name == "") and (rhcos_image_file_result['stat']['exists'] == true)

